apiVersion: v1
kind: LimitRange
metadata:
  name: aegisai-limits-team
  annotations:
    aegisai.io/limit-tier: team
spec:
  limits:
    - max:
        cpu: '4'
        memory: 8Gi
      min:
        cpu: 10m
        memory: 32Mi
      default:
        cpu: 200m
        memory: 256Mi
      defaultRequest:
        cpu: 50m
        memory: 128Mi
      type: Container
