apiVersion: v1
kind: LimitRange
metadata:
  name: aegisai-limits-security
  annotations:
    aegisai.io/limit-tier: security
spec:
  limits:
    - max:
        cpu: "2"
        memory: 4Gi
      min:
        cpu: 10m
        memory: 32Mi
      default:
        cpu: 200m
        memory: 256Mi
      defaultRequest:
        cpu: 50m
        memory: 128Mi
      type: Container
