apiVersion: v1
kind: Namespace
metadata:
  name: aegisai-platform-metrics-server
  labels:
    aegisai.io/tier: platform
    aegisai.io/component: metrics-server
    pod-security.kubernetes.io/enforce: baseline
    pod-security.kubernetes.io/enforce-version: latest
