apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: argocd-appsets
  annotations:
    aegisai.io/component: argocd-appsets

resources:
  - cluster-generator.yaml
  - git-generator.yaml
  - matrix-generator.yaml

labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/managed-by: argocd
      app.kubernetes.io/part-of: argocd
