apiVersion: monitoring.coreos.com/v1
kind: Alertmanager
metadata:
  name: main
  namespace: aegisai-observability
  labels:
    app.kubernetes.io/name: main
    app.kubernetes.io/component: alertmanager
spec:
  version: v0.27.0
  replicas: 1
  logLevel: info
  resources:
    requests:
      cpu: 100m
      memory: '128Mi'
    limits:
      cpu: '500m'
      memory: '512Mi'
  priorityClassName: observability-default
  storage:
    volumeClaimTemplate:
      spec:
        storageClassName: standard
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi
  nodeSelector:
    kubernetes.io/os: linux
  tolerations:
    - effect: NoSchedule
      key: node-role.kubernetes.io/infra
      operator: Exists
  podMetadata:
    labels:
      aegisai.io/metrics: prometheus
