apiVersion: v1
kind: Secret
metadata:
  name: argocd-notifications-secret
  labels:
    app.kubernetes.io/name: argocd-notifications-secret
    app.kubernetes.io/part-of: argocd
stringData:
  slack-token: CHANGE_ME
  email-password: CHANGE_ME
