apiVersion: v1
kind: Namespace
metadata:
  name: aegisai-platform-ingress-nginx
  labels:
    aegisai.io/tier: platform
    aegisai.io/component: ingress-nginx
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/enforce-version: latest
