apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: environment-prod
  namespace: argocd
  labels:
    app.kubernetes.io/name: environment-prod
    app.kubernetes.io/part-of: argocd
    aegisai.io/environment: prod
  annotations:
    argocd.argoproj.io/sync-wave: '0'
spec:
  description: Production environment project
  sourceRepos:
    - '*'
  destinations:
    - namespace: 'aegisai-*-prod'
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
  syncWindows:
    - kind: deny
      schedule: '0 8 * * 1-5'
      duration: 14h
      applications:
        - '*'
    - kind: allow
      schedule: '0 22 * * *'
      duration: 1h
      applications:
        - '*'
  orphanedResources:
    warn: true
