apiVersion: v1
kind: ResourceQuota
metadata:
  name: aegisai-quota-team
  annotations:
    aegisai.io/quota-tier: team
spec:
  hard:
    pods: "50"
    requests.cpu: "8"
    requests.memory: 32Gi
    limits.cpu: "16"
    limits.memory: 64Gi
    configmaps: "20"
    secrets: "20"
    persistentvolumeclaims: "10"
    services: "10"
