apiVersion: v1
kind: ResourceQuota
metadata:
  name: aegisai-quota-addon
  annotations:
    aegisai.io/quota-tier: addon
spec:
  hard:
    pods: "20"
    requests.cpu: "4"
    requests.memory: 16Gi
    limits.cpu: "8"
    limits.memory: 32Gi
    configmaps: "10"
    secrets: "10"
    services: "5"
