apiVersion: v1
kind: Namespace
metadata:
  name: aegisai-addon-cluster-autoscaler
  labels:
    aegisai.io/tier: addon
    aegisai.io/component: cluster-autoscaler
    pod-security.kubernetes.io/enforce: baseline
    pod-security.kubernetes.io/enforce-version: latest
