apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: environment-dev
  namespace: argocd
  labels:
    app.kubernetes.io/name: environment-dev
    app.kubernetes.io/part-of: argocd
    aegisai.io/environment: dev
  annotations:
    argocd.argoproj.io/sync-wave: '0'
spec:
  description: Development environment project
  sourceRepos:
    - '*'
  destinations:
    - namespace: 'aegisai-*-dev'
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
  syncWindows:
    - kind: allow
      schedule: '0 0 * * *'
      duration: 168h
      applications:
        - '*'
  orphanedResources:
    warn: true
