apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: aegisai-efs
  labels:
    aegisai.io/storage-tier: shared
provisioner: efs.csi.aws.com
reclaimPolicy: Delete
volumeBindingMode: Immediate
mountOptions:
  - tls
  - rsize=1048576
  - wsize=1048576
  - hard
  - timeo=600
  - retrans=2
  - noresvport
