{{- $appName := (index .Values "aegisai-common").nameOverride }}
apiVersion: apiregistration.k8s.io/v1
kind: APIService
metadata:
  name: v1beta1.metrics.k8s.io
  labels:
    helm.sh/chart: {{ printf "%s-%s" .Chart.Name .Chart.Version | replace "+" "_" | trunc 63 | trimSuffix "-" }}
    app.kubernetes.io/name: {{ $appName }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    app.kubernetes.io/component: {{ .Values.component }}
    app.kubernetes.io/part-of: {{ .Values.partOf }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    aegisai.io/environment: {{ .Values.global.environment }}
    aegisai.io/tier: {{ .Values.global.tier }}
    aegisai.io/data-classification: {{ .Values.global.dataClassification }}
    aegisai.io/owner: {{ .Values.global.owner }}
    aegisai.io/cost-center: {{ .Values.global.costCenter }}
  annotations:
    aegisai.io/environment: {{ .Values.global.environment }}
    aegisai.io/owner: {{ .Values.global.owner }}
    aegisai.io/cost-center: {{ .Values.global.costCenter }}
    aegisai.io/data-classification: {{ .Values.global.dataClassification }}
    aegisai.io/compliance-frameworks: pci-dss,soc2,rbi
spec:
  service:
    name: {{ $appName }}
    namespace: {{ .Release.Namespace }}
  group: metrics.k8s.io
  version: v1beta1
  groupPriorityMinimum: 100
  versionPriority: 100
  insecureSkipTLSVerify: true
