apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: environment-prod
  namespace: argocd
  labels:
    app.kubernetes.io/name: environment-prod
    app.kubernetes.io/part-of: platform
  annotations:
    argocd.argoproj.io/sync-wave: '6'
spec:
  project: environment-prod
  source:
    repoURL: https://github.com/novapay/novapay-ai-devops
    targetRevision: HEAD
    path: kubernetes/envs/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
      - ApplyOutOfSyncOnly=true
      - RespectIgnoreDifferences=true
    retry:
      limit: 5
      backoff:
        duration: 30s
        factor: 2
        maxDuration: 5m
