apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: alertmanager-main
  namespace: aegisai-observability
  labels:
    app.kubernetes.io/name: alertmanager
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: aws-secrets-manager
  target:
    name: alertmanager-main
    creationPolicy: Owner
  data:
    - secretKey: alertmanager.yaml
      remoteRef:
        key: /aegisai/observability/alertmanager/config
        property: alertmanager.yaml
